// =============chapter 3 Assignment===================
// 1. Declare a variable called age & assign to it your age. Show
// your age in an alert box.
// let age= 30;
// alert("I am "+ age + " years old");

// ===================================================================================

// 2. Declare & initialize a variable to keep track of how many
// times a visitor has visited a web page. Show his/her
// number of visits on your web page. For example: “You
// have visited this site N times”
// let N= 14
// // alert("You have visited this site " + N +" times");


// =======================================================================================

// 3. Declare a variable called birthYear & assign to it your
// birth year. Show the following message in your browser:

// let birthyear= 1990
// document.write("My birth year is " + birthyear);
// document.write("<br>");
// document.write("Data type of my decleared variable is number");

// =======================================================================================

// 4. A visitor visits an online clothing store
// www.xyzClothing.com . Write a script to store in variables
// the following information:
// a. Visitor’s name
// b. Product title
// c. Quantity i.e. how many products a visitor wants to
// order
// Show the following message in your browser: “John
// Doe ordered 5 T-shirt(s) on XYZ Clothing store”

// let visitorsName= "Naila Nasrullah";
// let product=" T-Shirts";
// let quantity= 15;
// document.write(visitorsName + " odered " + quantity +  product +" on Outfiltter store");






